### ISSUE TITLE
update-resolv-conf does not work on Alpine

### ISSUE THREAD

**Issue by cscetbon** [cdrage/dockerfiles#1]
Hey @cdrage,

There are issues with https://github.com/cdrage/dockerfiles/tree/master/openvpn-client :

- Alpine does not have bash by default so the bash script you add can't run...
- `/sbin/resolvconf` does not exist on Alpine. You can install `openresolv` to get that script
- dhcp search options are not supported with the current script

However everything works well with https://github.com/cdrage/dockerfiles/tree/master/openvpn-client-docker

**Comment by cdrage** [comment]
@cscetbon 

Yeah! I haven't used that Dockerfile for agggessss. I actually took it from: https://github.com/jessfraz/dockerfiles/tree/master/openvpn (forgot to add source).

In the middle of trying to fix something with it it looks like I re-added update-resolv which makes zero sense since like you mentioned it doesn't contain bash!

Are you able to perhaps push a PR to fix the Dockerfile if you happen to find the way to fix it? You mentioned regarding installing openresolv.

**Comment by cscetbon** [comment]
Here it is https://github.com/cdrage/dockerfiles/pull/2

**Comment by cdrage** [comment]
@cscetbon 

Merged! Thanks for the fix :+1:
